version: '3.9'

services:
  app:
    image: node:18-alpine
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URI=${DB_URI}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PUBLIC_PROD=${PUBLIC_PROD}
      - PUBLIC_MOBILE=${PUBLIC_MOBILE}
    depends_on:
      - neo4j
      - api
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URI=${DB_URI}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=4000
      - PROD=${PUBLIC_PROD}
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.12
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/{DB_PASSWORD}
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_config_strict__validation_enabled=false

volumes:
  neo4j-data: