version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-castify
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/citrus-atomic-spend-water-dream-8091

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - name=value
      - JWT_SECRET=MY_SUPER_SECRET_KEY
      - NEO4J_URL=neo4j://localhost:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=citrus-atomic-spend-water-dream-8091
      - PORT=4000
      - NODE_ENV=production
    depends_on:
      - neo4j

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_GRAPHQL_ENDPOINT=http://api:4000/graphql
    depends_on:
      - api

