version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports: # TODO: move to expose eventually because we're using nginx
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /mnt/neo4j/data:/data
      - /mnt/neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: # TODO: move to expose eventually because we're using nginx
      - "${API_PORT}:${API_PORT}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NEO4J_URL=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - PORT=${API_PORT}
      - NODE_ENV=production
    depends_on:
      - neo4j

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
        PROD: ${PROD}
        MOBILE: false
    ports: # TODO: move to expose eventually because we're using nginx
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    environment:
      - PROD=${PROD}
      - MOBILE=false
    depends_on:
      - api
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - webapp
      - api

