version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "${API_PORT}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - PORT=${API_PORT}
      - NODE_ENV=production

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
        PROD: ${PROD}
        MOBILE: false
    expose:
      - "${WEBAPP_PORT}"
    environment:
      - PROD=${PROD}
      - MOBILE=false
    depends_on:
      - api
