create table COMMENTS_ON (
	episodeId VARCHAR(50),
	userId VARCHAR(50),
	commentDesc TEXT,
	commentDate DATE,
	timestampStart INT,
	timestampEnd INT
);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('85', '15', 'duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', '2022-04-14', 3912, 3942);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('63', '4', 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', '2022-04-18', 9004, 9058);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('32', '5', 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', '2021-12-25', 6392, 6456);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('1', '11', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', '2022-07-15', 9580, 9676);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('46', '18', 'penatibus et magnis dis parturient montes nascetur ridiculus mus', '2022-03-01', 1423, 1508);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('6', '13', 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien', '2022-01-15', 4648, 4724);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('34', '3', 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', '2022-03-06', 3910, 3982);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('75', '12', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', '2022-01-13', 1387, 1418);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('43', '1', 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet', '2022-05-12', 7021, 7069);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('96', '19', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', '2022-05-26', 4077, 4147);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('99', '10', 'eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet', '2022-02-13', 4821, 4876);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('93', '17', 'vel lectus in quam fringilla', '2022-10-24', 1664, 1702);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('28', '16', 'morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', '2022-02-26', 1199, 1295);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('79', '6', 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus', '2022-03-25', 6140, 6191);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('13', '8', 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus', '2022-03-08', 7538, 7588);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('77', '14', 'vel sem sed sagittis nam congue risus semper', '2022-10-08', 6444, 6466);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('20', '2', 'nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', '2022-10-04', 5066, 5150);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('24', '7', 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod', '2022-04-28', 750, 801);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('86', '20', 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque', '2022-08-13', 3830, 3864);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('7', '9', 'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque', '2022-09-21', 1741, 1827);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('74', '7', 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam', '2022-02-04', 5120, 5192);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('5', '19', 'ut nulla sed accumsan felis ut', '2022-03-27', 8321, 8397);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('18', '10', 'ac leo pellentesque ultrices mattis odio', '2022-01-08', 674, 688);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('51', '9', 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo', '2022-05-07', 5566, 5588);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('19', '1', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit', '2022-11-10', 1652, 1666);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('45', '4', 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci', '2022-08-18', 7012, 7091);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('4', '18', 'rutrum nulla tellus in sagittis dui vel', '2022-02-13', 7413, 7440);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('29', '16', 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', '2022-01-28', 1256, 1325);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('21', '8', 'placerat praesent blandit nam nulla', '2022-06-08', 1170, 1269);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('10', '2', 'eget vulputate ut ultrices vel augue', '2022-04-06', 1589, 1676);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('90', '3', 'etiam pretium iaculis justo in hac habitasse platea', '2022-04-10', 6871, 6886);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('52', '17', 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', '2022-11-20', 7834, 7865);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('70', '5', 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', '2022-07-14', 6625, 6678);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('64', '13', 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', '2022-09-02', 7634, 7684);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('37', '15', 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit', '2022-08-09', 7751, 7819);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('94', '12', 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', '2022-09-03', 5527, 5568);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('72', '14', 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', '2022-11-08', 7678, 7722);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('2', '6', 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', '2022-05-12', 8377, 8413);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('81', '11', 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum', '2022-11-07', 2949, 3043);
insert into COMMENTS_ON (episodeId, userId, commentDesc, commentDate, timestampStart, timestampEnd) values ('25', '20', 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst', '2022-04-25', 978, 1059);
