# schema.graphql

# ------------------------------------------------------------
# --------------------- Object Types -------------------------
# ------------------------------------------------------------

type User {
    id: ID
    username: String
    email: String
    password: String
    joinDate: Date

    #firstName: String
    #lastName: String
    #lastLoginDate: Date
    #profileImage: String
    #bio: String
}

input RegisterInput {
	username: String
	email: String
	password: String
}

input LoginInput {
	email: String
	password: String
}

input AddPodcastInput {
    rssUrl: String
}

type FollowerRelation {
    follower: User!
    followed: User!
    since: Date!
}

type Podcast {
    id: ID
    title: String
    description: String
    url: String
    image: String
    lastUpdated: DateTime
    episodes: [Episode!]! @relationship(type: "HAS_EPISODE", direction: OUT)
}

type Episode {
    id: ID
    title: String
    description: String
    image: String
    url: String
    releaseDate: DateTime
    duration: Int
    producedBy: Podcast! @relationship(type: "HAS_EPISODE", direction: IN)
}

# ------------------------------------------------------------
# -------------------- Mutation Types ------------------------
# ------------------------------------------------------------

type Mutation {
    
    # Users
    registerUser(registerInput: RegisterInput): User
	loginUser(loginInput: LoginInput): User
    logoutUser: Boolean!

    # Podcasts
    addPodcast(addPodcastInput: AddPodcastInput): Podcast
}

# ------------------------------------------------------------
# ---------------------- Query Types -------------------------
# ------------------------------------------------------------

type Query {
    
    # Users
	# user(id: ID!): User
    getCurrentUser: User

    # Podcasts
    # podcasts: [Podcast]
    # podcast(id: ID!): Podcast
}
